### ISSUE TITLE
数据库可否给全一点

### ISSUE THREAD

**Issue by fanjianqiang1989** [yuzd/AntMgr#2]
数据库可否给全一点，我把他改成MSSQL，数据不全，数据库数据权限表都没有

**Comment by yuzd** [comment]
哦 你的意思是要MSSQL的？
我用的是mysql 所以没有MSSQL哦。其实就是4张表加菜单和系统用户的初始化数据。
你参考mysql的初始化脚本修改下？
如果你修改好愿意贡献下吗？

**Comment by yuzd** [comment]
你用的myssql版本是多少？

**Comment by fanjianqiang1989** [comment]
sql2012

**Comment by fanjianqiang1989** [comment]
初始化数据不准。

**Comment by yuzd** [comment]
初始化数据不准，这个能否描述详细一些 ，比如有哪些表现

**Comment by shawdren** [comment]
@fanjianqiang1989 我用的也是ms sql， 跑起来基本没有问题的。
@yuzd 安装Ant.Data Code Gen的插件后，配置ant.db.json,生成代码报错，信息如下：

`Error happens: System.NullReferenceException: Object reference not set to an instance of an object.

   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)

   at LinqToDB.Data.CommandInfo.Execute[T]()

   at LinqToDB.Data.DataConnectionExtensions.Execute[T](DataConnection connection, String sql)

   at LinqToDB.DataProvider.SqlServer.SqlServerSchemaProvider.InitProvider(DataConnection dataConnection)

   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)

   at AntOrmCodeGen.AntOrmCodeGen.LoadServerMetadata(DataConnection dataConnection)

   at AntOrmCodeGen.AntOrmCodeGen.LoadMetadata(DataConnection dataConnection)

   at AntOrmCodeGen.AntOrmCodeGen.LoadSqlserverMetadata()

   at AntOrmCodeGen.AntOrmCodeGen.StartSqlServer(CodeGenOptions options)

   at AntDataVS.AntDataVSMenu.CommandSqlserverInvoke(Object sender, EventArgs e) in D:\root\myspace\AntDataVS\AntDataVS\AntDataVSMenu.cs:line 70`

我的配置文件是:
`{
  "NamespaceName": "DbModel", //必填：设置生成代码的命名空间

  "BaseEntityClass": "", //可选：生成的DTo继父类class名称

  "DataContextName": "AntEntity", //自定义生成的数据库Entity的name( 如果不填会有默认值为db的名称+Entitys)

  "EntitySuffix": "", //自定义生成的每张表对应class的后缀 例如统一加一个 "DTO"

  "AssociationPrefix": "", //定义生成外键的字段名称的前缀 例如 “FK_”

  "AssociationAppendByFieldName": true, //定义生成外键的字段名称是否根据增加 "By" + 他的字段名称

  "GenerateAssociations": false, //是否生成外键

  "ConnectionString": "Data Source=.;Initial Catalog=zant;User id=sa; Password=sa", //DB链接字符串

  "OutFileName": "DbModels", //生成的cs文件名称

  "SetFkList": [ //逻辑(非物理,不提倡物理建外键)
    //格式: A表名称，A表字段，B表名称，B表字段，外键关系(OneToOne,OneToMany,ManyToOne) 例如 "good_category,GoodTid,goods,Tid,OneToOne"
  ],
  "UsingList": [ //设置Using

  ],
  "SetColumnTypeList": [ //自定义设置属性的类型 格式为 table.filedName=xxxxxx  例如："person.Gender=GenderEnum"

  ]
}`

在VS2017和VS2019中都试过了，报的错误是一样的，空引用。

**Comment by yuzd** [comment]
@shawdren 谢谢你，关于MSSQL的codegen我稍等修复下告诉你

**Comment by shawdren** [comment]
> @shawdren 谢谢你，关于MSSQL的codegen我稍等修复下告诉你

不客气

**Comment by yuzd** [comment]
@fanjianqiang1989 我已经添加了MSSQL的初始化脚本,请拉取最新代码。脚本在 Dbmodel目录下
 另外代码默认用的是mysql 如果切换使用MSSQL 请查阅本项目wiki的第四篇文章

@shawdren  一键生成dbmodel 插件已修复更新 https://marketplace.visualstudio.com/items?itemName=nainaigu.AntDataVS

**Comment by shawdren** [comment]
@yuzd 生成成功了，谢谢

**Comment by yuzd** [comment]
我这边一直用mysql，如果你用sqlserver遇到什么问题请及时和我反馈哈
